### ISSUE TITLE
Feature 2: User Registration

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/primeapp-core-venkat#4]
#### User Story
* As a user, I should be able to register.

#### Fields: 
* Name. Mobile Number and Password

#### Table - "users"
* id,name,mobile_no,password, joined_on

* Joined On will be current date.

#### Validations:
*  Mobile No = 10 digit
*  Password = Length must be 8 or more characters

**Comment by venky-kumar** [comment]
####user can able to register with mobile number and name
* user id is auto generated
* password and re entered should be same
* joined on date will be auto generated
* mobile number validations are given and password length should be 8 or more characters
